### ISSUE TITLE
http2: stream closed

### ISSUE THREAD

**Issue by cerkauskas** [chartmogul/chartmogul-go#33]
Hello.

I am using your client and sometimes I get this error:
```
Request error: Post https://api.chartmogul.com/v1/customers/xxx/attributes/custom: http2: stream closed
```
As one could guess, this is happening when updating custom attributes.
I am using `AddCustomAttributesToCustomer` method of API structure. API client is initialized once and reused for all connections.
Information from Gopkg.lock:
```
[[projects]]
  digest = "1:c797a0c58a4a14307d4390b726bbb6da33ef55f94ebf8e6fe418bf9bfb104a89"
  name = "github.com/chartmogul/chartmogul-go"
  packages = ["."]
  pruneopts = "UT"
  revision = "b31285526784d898de6e9eac819739105a8640ef"
  version = "v1.2.5"
```

Is this a bug?

**Comment by hassansin** [comment]
@cerkauskas yes, unfortunately our nginx version doesn't support HTTP/2 yet. You have to disable HTTP2 when using ChartMogul API.

**Comment by pkopac** [comment]
@cerkauskas
Run with `GODEBUG=http2client=0`
https://golang.org/pkg/net/http/
