### ISSUE TITLE
Request hanged for more than 1 hour

### ISSUE THREAD

**Issue by zhenzou** [chartmogul/chartmogul-go#58]
The API's internal create and list method will retry forever if got the 429 and can not pass the context to the ChartMogul API.

It is VERY DANGEROUS to a SDK and it is not idioms in golang.

In our integration
1. we publish the invoice to the GCP pubsub
2. import to the ChartMogul via a push subscription
3. we have some businesses after requested to the ChartMogul
4. the CGP will abort and retry if the processing takes more than 30s.

And for some reason, we may publish lots of invoice in a short time, and it maybe take more than 30s(because the internal retry) to request to the ChartMogul, the GCP will start a new request to retry, and the old request still be hanged and retry for too many request.

So it will not take much times, all request have to retry for more than 30s when request to the ChartMogul, and all request will failed, and all request will retry, and the system is hanged.

Please consider add the context to the parameters or add the retry time configuration..

**Comment by pkopac** [comment]
Hello @zhenzou! Thank you for the report! It is indeed my fault from 5 years ago #2 I didn't allow the user to pass configuration for that. For reference [this is the retry code](https://github.com/chartmogul/chartmogul-go/blob/b79eb50a1a4adcf3dc7312c74a9dd5f9dd3e47e5/generic.go#L29-L39).

We can probably easily let you specify the retry configuration in some way, eg. set 0 retries (and upgrade the library to backoff v4). 
BTW, to be clear, are you saying the request to ChartMogul API takes 30+ seconds? Can you please specify which one it is? Do you mean [CreateInvoices](https://github.com/chartmogul/chartmogul-go/blob/v3/invoices.go#L74)?

**Comment by zhenzou** [comment]
@pkopac It it not the single reqeust take more than 30s. 

There are lots of request happens in the same time, so part of the requests will be throttled, and the SDK will retry forever until success.

If the whole retry processing take more than 30s, it will start new goroutine to retry, and **the old goroutine is still retrying to reqeust**, for some times there will be thousands of goroutine request to the ChartMogul API.

Because too much goroutine request at the same time, each goroutine have to take too much time to get the request to ChartMogul success. And even it request success, the context is timeout, and subsequent processing will be failed， it have to start again.


The whole reason is we can not abort the request to the ChartMogul unless we restart the whole process.

**Comment by pkopac** [comment]
@zhenzou thank you for the details. I would recommend to do the request(s) to ChartMogul asynchronously (eg. push a job to a queue, or start another goroutine). That way it won't influence the rest of your code's deadline. The limit of 30 seconds is quite short to be relied upon under all circumstances.

**Comment by zhenzou** [comment]
@pkopac It is hard to implement failover in async processing. And it will take us too much time to refactor our integration. 
Could you help to provider a way to remove the retry mechanism in the SDK，we will handle the retry by ourselves.
